version: "3"

services:
    php:
        build:
            context: ./apache
            dockerfile: ./Dockerfile
        restart: unless-stopped
        networks: 
            - iroha_net
        ports:
            - 10080:80
            - 10443:443
        depends_on:
            - mysql
        volumes:
            - ./apache/html:/var/www/html:rw
        tty: true
        stdin_open: true

    mysql:
        image: mysql
        restart: unless-stopped
        networks: 
            - iroha_net
        environment:
            - MYSQL_DATABASE=irohaboard
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Tokyo
        volumes:
            - ./apache/sql:/var/lib/mysql:rw
        tty: true
        stdin_open: true
networks: 
    iroha_net:
        driver: bridge