FROM ubuntu
LABEL version="0.1"
LABEL name="iroha"
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get -y upgrade \
	&& apt-get -y install zlib1g-dev apache2 php php-mysql libapache2-mod-php7.4 mysql-client 
ENV APACHE_DOCUMENT_ROOT /var/www/html
ENV APACHE_RUN_DIR /var/run/apache2
ENV PHP_INI_DIR /etc/php/7.4/apache2
COPY ./apache2.conf /etc/apache2/apache2.conf
COPY ./php.ini /etc/php/7.4/apache2/php.ini
COPY ./envvars /etc/apache2/envvars
#COPY ./html/ /var/www/html/
EXPOSE 443
RUN chown -R www-data /var/www/html
RUN service apache2 stop
RUN . /etc/apache2/envvars
ENV APACHE_RUN_USER=www-data
ENV APACHE_RUN_GROUP=www-data
ENV APACHE_PID_FILE=/var/run/apache2/apache2.pid
ENV APACHE_RUN_DIR=/var/run/apache2
ENV APACHE_LOCK_DIR=/var/lock/apache2
ENV APACHE_LOG_DIR=/var/log/apache2
ENV LANG=C